version: '3.1'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - "compiler"
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET} 
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    networks:
      - app-network

  compiler:
    build: ./compiler
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

